language: python
python:
  - "3.6"
install:
  - pip install xml2rfc
script:
  - xml2rfc draft-ytti-intarea-proxy-trace.xml
env:
  global:
    - secure: "gcRiG3v4ii4SSgNHH2hwoW+KWrQyfcBy24mAGHN6/hXtKQ4ONWJwTOkda4Ny3dLTC12Kcbqd4fuO55F3w4aKWMvkUfVnUPwdWxzJo5oYy2L3fU6cC5yVJRd3C6Isj1xzxvtMHmMRu37dHEw1+Il/jLORjbXoCkT2zD8hSqvW/WSg9zX3p+LSQs/Rgt6/ULz3jq19ne1uiKUn0Mt3tF7Y+9IG/D/X7PHgFzBC1Cy6LnPyxMuH7y03P0Ib2hCCn50bIFJOrAlVq9xr5g4+CWwyIKo/Rl2jXIN330v/H2+0v6leblbcX6ioWImyx4iI5F+dEN4gGIOu8AdR6MiqVuqudlm9F5jceqKAOnC5yXmAxmQEq3+3URPKupUF89fZ1BD4GEnNoLC//mAPE4mbm2liuaeOkSYNobN0A9QY1Yqon8iUSRhCbjFx4p+u8b9+/l0J69pKCuqGLAZa+E6QH2Bl0v0sgHQwnZvFng/CSLPoZl2jccAMDL/xWNXDajM6YXxMj2164ab2i7eOr63OYQqt7JJQYyF0gPVdFtGSMV5IIvpPSLR4q5Nr9peyFWszjmUxOSC6AvjeQ+BNNUyPsT4sQKpX2neq3DrwH0h6DWz7KSsP7s9k6a3l0GTd/Itl+UNXql2pruNP0AzLZ3DaY5VsWE9jcCR/Qfo4EGQ1QDXnd/4="
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PROXY_TRACE_GH_PAGES_TOKEN
  keep-history: true
  on:
    branch: master
